export enum Localization {
  LOGIN = 'Login',
  REG = 'Register',
  REGISTRATION = 'Registration',
  EnterLogin = 'EnterLogin',
  EnterPassword = 'EnterPassword',
  Min2Chars = 'Min2Chars',
  Min8Chars = 'Min8Chars',
  FieldRequired = 'FieldRequired',
  PasswordsNotMatch = 'PasswordsNotMatch',
  RepeatPassword = 'RepeatPassword',
  CheckEmail = 'CheckEmail',
  EnterEmail = 'EnterEmail',
  Documents = 'Documents',
  ManagementDocuments = 'ManagementDocuments',
  ManagementDepartments = 'ManagementDepartments',
  DocumentsInReview = 'DocumentsInReview',
  FunctionsTitle = 'FunctionsTitle',
  DocumentTable = 'DocumentTable',
  DepartmentTable = 'DepartmentTable',
  UserTable = 'UserTable',
  LogOut = 'LogOut',
}
